"""add column bill participant

Revision ID: 5882ce18ade1
Revises: b4b715020483
Create Date: 2025-09-18 11:19:33.715392

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5882ce18ade1"
down_revision: Union[str, None] = "b4b715020483"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "t_bill_participants", sa.Column("name", sa.String(length=100), nullable=True)
    )
    op.drop_index(op.f("ix_t_bills_bill_file_id"), table_name="t_bills")
    op.drop_constraint(op.f("t_bills_bill_file_id_fkey"), "t_bills", type_="foreignkey")
    op.drop_constraint(
        op.f("t_bills_payment_file_id_fkey"), "t_bills", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("t_bills_payment_file_id_fkey"),
        "t_bills",
        "t_file_systems",
        ["payment_file_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("t_bills_bill_file_id_fkey"),
        "t_bills",
        "t_file_systems",
        ["bill_file_id"],
        ["id"],
    )
    op.create_index(
        op.f("ix_t_bills_bill_file_id"), "t_bills", ["bill_file_id"], unique=False
    )
    op.drop_column("t_bill_participants", "name")
    # ### end Alembic commands ###
