"""update auth

Revision ID: 9d241fd441a3
Revises: 5882ce18ade1
Create Date: 2025-09-19 21:09:08.959301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d241fd441a3'
down_revision: Union[str, None] = '5882ce18ade1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_auth_token', 'user_id',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('t_user_profiles', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.add_column('t_user_profiles', sa.Column('avatar', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user_profiles', 'avatar')
    op.drop_column('t_user_profiles', 'birthday')
    op.alter_column('t_auth_token', 'user_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###
