"""init model bill

Revision ID: b4b715020483
Revises: 3ea2b095a373
Create Date: 2025-09-15 09:17:35.297114

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b4b715020483'
down_revision: Union[str, None] = '3ea2b095a373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        't_file_systems',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('file_name', sa.String(length=255), nullable=False),
        sa.Column('file_path', sa.Text(), nullable=False),
        sa.Column('file_type', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.String(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_by', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_file_systems_id'), 't_file_systems', ['id'], unique=True)
    op.create_table(
        't_bills',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('bill_number', sa.String(length=100), nullable=False),
        sa.Column('bill_file_id', sa.Integer(), nullable=True),
        sa.Column('type', sa.SmallInteger(), nullable=False),
        sa.Column('share_type', sa.SmallInteger(), nullable=False),
        sa.Column('status', sa.SmallInteger(), nullable=False),
        sa.Column('subtotal', sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column('tax_flag', sa.Boolean(), nullable=False),
        sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('tax_amount', sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column('tip_flag', sa.Boolean(), nullable=False),
        sa.Column('tip_percent', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('tip_amount', sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=10), nullable=False),
        sa.Column('number_people', sa.Integer(), nullable=False),
        sa.Column('payment_flag', sa.Boolean(), nullable=False),
        sa.Column('payment_method', sa.SmallInteger(), nullable=True),
        sa.Column('payment_note', sa.Text(), nullable=True),
        sa.Column('payment_file_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.String(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_by', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['bill_file_id'], ['t_file_systems.id'], ),
        sa.ForeignKeyConstraint(['payment_file_id'], ['t_file_systems.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_bills_bill_file_id'), 't_bills', ['bill_file_id'], unique=False)
    op.create_index(op.f('ix_t_bills_bill_number'), 't_bills', ['bill_number'], unique=True)
    op.create_index(op.f('ix_t_bills_id'), 't_bills', ['id'], unique=True)
    op.create_table(
        't_bill_items',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('bill_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('unit_price', sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.String(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_by', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['bill_id'], ['t_bills.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_bill_items_bill_id'), 't_bill_items', ['bill_id'], unique=False)
    op.create_index(op.f('ix_t_bill_items_id'), 't_bill_items', ['id'], unique=True)
    op.create_table(
        't_bill_participants',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('bill_id', sa.Integer(), nullable=False),
        sa.Column('bill_item_id', sa.Integer(), nullable=True),
        sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('payment_flag', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.String(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_by', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['bill_id'], ['t_bills.id'], ),
        sa.ForeignKeyConstraint(['bill_item_id'], ['t_bill_items.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_bill_participants_bill_id'), 't_bill_participants', ['bill_id'], unique=False)
    op.create_index(op.f('ix_t_bill_participants_bill_item_id'), 't_bill_participants', ['bill_item_id'], unique=False)
    op.create_index(op.f('ix_t_bill_participants_id'), 't_bill_participants', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_bill_participants_id'), table_name='t_bill_participants')
    op.drop_index(op.f('ix_t_bill_participants_bill_item_id'), table_name='t_bill_participants')
    op.drop_index(op.f('ix_t_bill_participants_bill_id'), table_name='t_bill_participants')
    op.drop_table('t_bill_participants')
    op.drop_index(op.f('ix_t_bill_items_id'), table_name='t_bill_items')
    op.drop_index(op.f('ix_t_bill_items_bill_id'), table_name='t_bill_items')
    op.drop_table('t_bill_items')
    op.drop_index(op.f('ix_t_bills_id'), table_name='t_bills')
    op.drop_index(op.f('ix_t_bills_bill_number'), table_name='t_bills')
    op.drop_index(op.f('ix_t_bills_bill_file_id'), table_name='t_bills')
    op.drop_table('t_bills')
    op.drop_index(op.f('ix_t_file_systems_id'), table_name='t_file_systems')
    op.drop_table('t_file_systems')
    # ### end Alembic commands ###
